wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.32.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696388578.964003
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.8.16
      5: 0.15.7
      6: 4.32.0.dev0
      8:
      - 1
      - 5
